name: Publish Tag

on:
  push:
    tags:
      - v*.*.* # Push events to v1.0.0, ...

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract changelog
        run: | 
          VERSION="$(npm run --silent getVersion)"
          cat CHANGELOG.md | sed -n "/## \[${VERSION}\]/,/## \[/p" | tail -n +2 | sed -e '$ d' > CHANGELOG_CURRENT_VERSION.md

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG_CURRENT_VERSION.md
          draft: false
          prerelease: false